[build]
aptPackages = [
  "libx11-6",
  "libxrandr2",
  "libxinerama1",
  "libxi6",
  "libxtst6",
  "libxcursor1",
  "libxss1",
  "libxcomposite1",
  "libasound2",
  "libpangoft2-1.0",
  "libpango-1.0-0",
  "libgconf-2-4",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libxkbcommon0",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxkbcommon-x11-0",
  "libgbm1",
  "libnspr4",
]
